#
# DEVELOPMENT
# Dockerfile
#

#
# In DEVELOPMENT mode we
# not use Multi-staging
# only in PRODUCTION
#
# We install the dependencies
# and required tools such as git, npm
#

FROM mhart/alpine-node:12

WORKDIR /usr/src/express-dev-env

COPY . /usr/src/express-dev-env

RUN apk update && apk add --no-cache git
RUN npm ci --ignore-scripts
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

ENV NODE_CLUSTER_SCHED_POLICY=rr
ENV NODE_ENV=development

EXPOSE 8080

CMD ["npm", "run", "dev"]
