#
# DEVELOPMENT
# Dockerfile
#

#
# In DEVELOPMENT mode we
# not use Multi-staging
# only in PRODUCTION
#
# We install the dependencies
# and required tools such as git, npm
#

FROM mhart/alpine-node:12

RUN apk update && apk add --no-cache git
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

WORKDIR /usr/src/app

COPY app /usr/src/app

RUN npm i nodemon -g
RUN npm ci

CMD ["nodemon", "./usr/src/app/server.js"]
