#
# DEVELOPMENT
# Dockerfile
#

#
# In DEVELOPMENT mode we
# not use Multi-staging
# only in PRODUCTION
#
# We install the dependencies
# and required tools such as git, npm
#

FROM mhart/alpine-node:12

WORKDIR /usr/src/uws-app

COPY . /usr/src/uws-app

RUN apk update && apk add --no-cache git
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

RUN npm ci --ignore-scripts

ENV NODE_CLUSTER_SCHED_POLICY=rr
ENV PORT=8080

EXPOSE 8080

CMD ["npm", "run", "dev"]
